spring:
  datasource:
    url:  jdbc:mariadb://121.140.84.254:3306/web_dev
    #url: jdbc:log4jdbc:h2:tcp://localhost/~/devlsy-service1;MODE=mariadb
    username: aselcni
    password: asel42911!
    driver-class-name: org.mariadb.jdbc.Driver

server:
  port: 80
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

logging:
  level:
    kr:
      co:
        biztax:
          aselas:
            repository: trace